Update swift-sonar-analysis.yml
Signed-off-by: adityankannan-tw <109274996+adityankannan-tw@users.noreply.github.com>

diff --git a/.github/workflows/swift-sonar-analysis.yml b/.github/workflows/swift-sonar-analysis.yml
--- a/.github/workflows/swift-sonar-analysis.yml
+++ b/.github/workflows/swift-sonar-analysis.yml
@@ -67,12 +67,14 @@ jobs:
         run: |
           cd ${{ inputs.SERVICE_LOCATION }}
 
+           # Check if Tests directory exists and is not empty
+          if [ -d "Tests" ] && [ "$(ls -A Tests)" ]; then
           swift test --enable-code-coverage
 
           # Verify coverage data exists before merging
           if [ ! -f .build/debug/codecov/default.profdata ]; then
-            echo "Error: Coverage data file (.profdata) not found!"
-            exit 1
+          echo "Error: Coverage data file (.profdata) not found!"
+          exit 1
           fi
 
           # Merging coverage data
@@ -80,7 +82,11 @@ jobs:
 
           # Generating coverage report
           xcrun --run llvm-cov show -instr-profile=.build/debug/codecov/profdata.profdata .build/debug/*PackageTests.xctest/Contents/MacOS/*PackageTests > coverage.report
-
+          else
+          echo "No tests found. Creating empty coverage report for sonar."
+          touch coverage.report
+          fi
+          
       - name: Run Sonar Analysis
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
